### ISSUE TITLE
Name vcf-files by UID? label:question

### ISSUE THREAD

**Issue by zodtm** [ppladdressbook/ppl#47]
First of all: great piece of software. Exactly what I was looking for!

While I really like the concept of using git for sync, one thing that is still missing is the ability to sync to smartphones. Here vdirsyncer ( https://github.com/untitaker/vdirsyncer ) could do the trick.
From a quick check it seems to me, that a "vdir" is basically the same as ppl's storage backend with the names of the vcf-files being some UID string.

**Comment by untitaker** [comment]
I'm not at all familiar with Ruby, but I think it is a good solution to store the ``GreenCard::Vcard`` object on the ``Contact`` instance, and re-use it when encoding. While that would create a "dirty" attribute for the ``Contact`` class, it still avoids making the code more vcard-specific than other solutions.

**Comment by DamienCassou** [comment]
Any update?

**Comment by hnrysmth** [comment]
Hey @untitaker I know I've been a crappy maintainer this year. If you're still interested in working on this I'll be more than happy to add you as a proper collaborator to the project so that you don't have to worry about your work sitting unused because of me :flushed:

**Comment by untitaker** [comment]
I'm not particularly interested atm but I've hit a problem while working on #52. See comments there.

**Comment by hnrysmth** [comment]
Gonna close this issue actually.
