### ISSUE TITLE
export birthdays as recurring events in a single vCalendar object

### ISSUE THREAD

**Issue by sharethewisdom** [ppladdressbook/ppl#53]
I'm not a programmer as such, so I just sharing the idea. There's probably a straightforward Ruby tool for this, or otherwise, maybe a [Python](http://vobject.skyhouseconsulting.com/) script could be written? 

I think it would be useful to export birthdays using ppl, not just because you can write a title like *firstname's birthday* but mainly because you can have the complete contact info in the description. Also, one of the reasons I like ppl is because I'm too stupid to get the age of a person on his/her birthday right :) A recurring event won't help me be confident about the age per se, unless I also write a short table of dates and ages to the description as a mnemonic. 

On a related note, and i haven't tried it: to be notified for a birthday using [birthday](http://www.freshports.org/misc/birthday/) one could simply write `bd name=DD/MM/YYYY` to `~/.birthdays`. It's probably easy to use ppl's bang alias feature for that.

**Comment by untitaker** [comment]
I've found https://github.com/reinteractive-open/vpim-rails-reinteractive/blob/master/samples/vcf-to-ics.rb, I'd be glad if somebody wrote something more lightweight (less dependencies), or better maintained.

**Comment by hnrysmth** [comment]
Would totally accept a PR adding this. I'm unlikely to make time to build it myself though. So for now I'm gonna leave this issue closed as there's nothing left to do until somebody submits a PR.
