### ISSUE TITLE
Could not successfully read contacts in one .vcf file

### ISSUE THREAD

**Issue by envolyse** [ppladdressbook/ppl#55]
'Nuf said, I have one file with all my contacts and I would like to read it, but seems ppl stops reading file after first contact from top.

**Comment by hnrysmth** [comment]
Yep this is by design, sorry. ppl works on a basis of one contact per .vcf file. The whole thing is architected really tightly around that assumption so it's one we're stuck with I'm afraid. Sorry!

**Comment by envolyse** [comment]
Yeah, but it could be possible to an option to split one file like this into multiple ones

**Comment by hnrysmth** [comment]
Oh wow that's a fun thought actually. I'm imagining a .vcf file containing multiple vcard records, maybe called contacts.vcf for example. We could have a command line interaction like....

```bash
$ ppl import contacts.vcf
Successfully imported 10 contacts
```

Is that the kind of thing you're thinking of?

**Comment by untitaker** [comment]
There are unfortunately two ways to represent multiple VCARDS in a file FYI. Once wrapped in a VADDRESSBOOK, and once just a bunch of VCARDS concatenated together.

**Comment by envolyse** [comment]
>Is that the kind of thing you're thinking of?
Yes, exactly what I want :)

> There are unfortunately two ways to represent multiple VCARDS in a file FYI. Once wrapped in a VADDRESSBOOK, and once just a bunch of VCARDS concatenated together.

Didn't saw first one yet, but most of export-like apps for android export them in a file containing a bunch of vcards.
