### ISSUE TITLE
Some questions about features and refactoring

### ISSUE THREAD

**Issue by acant** [ppladdressbook/ppl#67]
First, my thanks to @hnrysmth for building and maintaining this project. Storing contacts in a git repo was just what I was looking for and I have used it for a few years now. Hopefully, I can help out, too.

I am wondering about adding some new features and doing some refactoring, but I wanted to check whether these would fit with the project before I start making changes.

# New Features
* add a [UID](https://tools.ietf.org/html/rfc6350#section-6.7.6) field to the card
* use the [vdir storage format](https://vdirsyncer.pimutils.org/en/stable/vdir.html), using the UID for the filename
* add a [KIND](https://tools.ietf.org/html/rfc6350#section-6.1.4) to allow organization and group support
* add [RELATED](https://tools.ietf.org/html/rfc6350#section-6.6.6)
* add a free text storage for each contact
  - [Note](https://tools.ietf.org/html/rfc6350#section-6.7.2) field in the vCard is one idea
  - storing another text file beside the vCard

I think that I would like to add more vCard fields, but these are the ones that I was hoping to get started with.

# Refactoring and tooling
* get TravisCI properly configured, running but seems to be showing an error
* add the CodeClimate test coverage tool
* add rubocop
* add gemnasium
* add inchci

# Question
* would you consider using [Thor](https://github.com/erikhuda/thor) for the CLI commands?
* is it worth investigating using [vcard](https://rubygems.org/gems/vcard) to support more vCard fields? Or is the way greencard works have a more fundamental difference that I am not appreciating?

**Comment by hnrysmth** [comment]
This is all absolute gold @acant. You've probably noticed from the commit logs that not much happens in this project these days. I got to a point with this code where I'd implemented everything I personally wanted. But if there's more you'd like, I'd say go for it. I can add you to the GitHub org if you'd like.

That `greencard` gem was created by me. It's a fork from vpim and was supposed to be a _temporary_ hack workaround for an issue I can't quite remember the specifics of. See issue #17 for an example of the kind of bug. Anyway that `vcard` gem is also straight out of vpim so it should be 100% good to go. If it has more functionality now then awesome!

The storage format thing I think sounds fine. In the past I very much wanted the storage directory to be a somewhat human-readable place where you could go and feel like "oh here's my data I recognize these names nice this all makes sense". In the past I've resisted requests to change this but I'm over it now. I'd say version it as a BC breaking change (major version bump) but apart from that :+1:

Everything else you suggest sounds fine too, just those above points were the only two things where I could think of extra helpful info to provide 😄

**Comment by untitaker** [comment]
>use the vdir storage format, using the UID for the filename

FWIW this is not a problem that is keeping vdirsyncer from being compatible with ppl. The filename is pretty much irrelevant to it, and ppl can continue to assign meaning to it if it wishes.

The bigger problem is that ppl, upon writing back vcards, is discarding unsupporting properties. This is sort of a dealbreaker when synchronizing with other vcard clients which may support those properties. See #58

**Comment by acant** [comment]
@hnrysmth  and @untitaker thank you both for the feedback. I'm going to start with splitting out some of the ideas that I mentioned into separate issues.

I won't try the filename change for the moment, as @untitaker has indicated that it is not critical for for vdir syncing. I will work on the UID field and handling relations first, and then see if the uid's in filenames still seem important.

I have not yet had a change to try out the [vcard gem](https://rubygems.org/gems/vcard), but I am hoping that it might help with the UID and RELATED fields. And now I am wondering if it might fix the un-handled fields problem too. Or at least provide a place to add more field support that can be used by other projects as well.

**Comment by acant** [comment]
I have open an linked a bunch of more specified issues, so I am going to close this one. 

@hnrysmth and @untitaker thanks again for your feedback. I am looking forward to making more contributions!
